version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.27.0
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    environment:
      - JWT_SECRET=${JWT_SECRET}
    command:
      - envoy
      - -c
      - /etc/envoy/envoy.yaml
      - --service-cluster
      - envoy-proxy
      - --service-node
      - envoy-proxy
      - -l
      - debug
    depends_on:
      - auth-service
      - elderly-service

  auth-service:
    build: 
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${AUTH_SERVICE_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - mongodb

  elderly-service:
    build:
      context: ./services/elderly-management-service
      dockerfile: Dockerfile
    ports:
      - "${ELDERLY_SERVICE_PORT}:${ELDERLY_SERVICE_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${ELDERLY_SERVICE_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
